### ISSUE TITLE
final exclude path can only have 2 values

### ISSUE THREAD

**Issue by tkhyn** [easy-webpack/config-json#1]
Hello,

I had trouble setting custom exclude paths. It seems that the expression used to set the exclude option needs brackets. Otherwise the 2 only possible values are `['/root/dir/node_modules']` or `[]` and the provided value is discarded.

``` javascript
exclude || this.metadata.root ? [path.join(this.metadata.root, 'node_modules')] : []
```

I'd think the following would be more appropriate (and my custom exclude paths were taken into account after that change):

``` javascript
exclude || (this.metadata.root ? [path.join(this.metadata.root, 'node_modules')] : [])
```

The same issue seems to be present in other presets ([config-babel](https://github.com/easy-webpack/config-babel) at least, and possibly others using loaders).

**Comment by niieani** [comment]
oh, my bad! great find, thanks! I think this bug will be present in most configs.

**Comment by tkhyn** [comment]
Glad it helped. Thanks for being so prompt and updating all the presets!
